# https://github.com/release-it/release-it/blob/master/config/release-it.json
git:
  commitMessage: 'chore: release v${version}'
github:
  release: true
  releaseName: 'v${version}'
  assets:
    - artifacts/*.dmg
    - artifacts/*.zip
    - artifacts/*.blockmap
    - artifacts/*.yml
hooks:
  before:release: npm run package
plugins:
  '@release-it/conventional-changelog': # https://github.com/release-it/conventional-changelog
    preset: angular
